version: '3.3'
volumes:
  db_data:

services:
  db:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_PORT: 3306
      MYSQL_DATABASE: alura
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
  app:
    build: .
    volumes:
      - .:/src
      - ./src:/code
    depends_on:
      - db
    links:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: alura
      MYSQL_ROOT_PASSWORD: secret
